/**
 * oui.js — MAC OUI (Organizationally Unique Identifier) vendor lookup
 *
 * Contains ~300 of the most common mobile/laptop OUIs seen on hotspots.
 * Keys are the first 3 octets lowercase (e.g. "e4:a7:c5").
 * Randomised/locally-administered MACs (bit 1 of first octet set) get special handling.
 */

// Format: "xx:xx:xx" → { vendor, type }
// type: "phone" | "laptop" | "tablet" | "router" | "iot" | "pc" | "unknown"
const OUI_DB = {
  // Apple
  "00:03:93": { vendor: "Apple",          type: "pc"     },
  "00:0a:27": { vendor: "Apple",          type: "pc"     },
  "00:0a:95": { vendor: "Apple",          type: "pc"     },
  "00:16:cb": { vendor: "Apple",          type: "pc"     },
  "00:17:f2": { vendor: "Apple",          type: "pc"     },
  "00:19:e3": { vendor: "Apple",          type: "pc"     },
  "00:1b:63": { vendor: "Apple",          type: "pc"     },
  "00:1c:b3": { vendor: "Apple",          type: "pc"     },
  "00:1d:4f": { vendor: "Apple",          type: "pc"     },
  "00:1e:52": { vendor: "Apple",          type: "pc"     },
  "00:1e:c2": { vendor: "Apple",          type: "pc"     },
  "00:1f:5b": { vendor: "Apple",          type: "pc"     },
  "00:1f:f3": { vendor: "Apple",          type: "pc"     },
  "00:21:e9": { vendor: "Apple",          type: "pc"     },
  "00:22:41": { vendor: "Apple",          type: "pc"     },
  "00:23:12": { vendor: "Apple",          type: "pc"     },
  "00:23:32": { vendor: "Apple",          type: "pc"     },
  "00:23:6c": { vendor: "Apple",          type: "pc"     },
  "00:24:36": { vendor: "Apple",          type: "pc"     },
  "00:25:00": { vendor: "Apple",          type: "pc"     },
  "00:25:4b": { vendor: "Apple",          type: "pc"     },
  "00:25:bc": { vendor: "Apple",          type: "pc"     },
  "00:26:08": { vendor: "Apple",          type: "pc"     },
  "00:26:4a": { vendor: "Apple",          type: "pc"     },
  "00:26:b9": { vendor: "Apple",          type: "pc"     },
  "00:26:bb": { vendor: "Apple",          type: "phone"  },
  "00:3e:e1": { vendor: "Apple",          type: "pc"     },
  "04:0c:ce": { vendor: "Apple",          type: "phone"  },
  "04:15:52": { vendor: "Apple",          type: "phone"  },
  "04:1e:64": { vendor: "Apple",          type: "phone"  },
  "04:26:65": { vendor: "Apple",          type: "phone"  },
  "04:48:9a": { vendor: "Apple",          type: "phone"  },
  "04:54:53": { vendor: "Apple",          type: "phone"  },
  "04:d3:cf": { vendor: "Apple",          type: "phone"  },
  "08:66:98": { vendor: "Apple",          type: "phone"  },
  "08:70:45": { vendor: "Apple",          type: "phone"  },
  "0c:3e:9f": { vendor: "Apple",          type: "phone"  },
  "0c:74:c2": { vendor: "Apple",          type: "phone"  },
  "0c:77:1a": { vendor: "Apple",          type: "phone"  },
  "10:1c:0c": { vendor: "Apple",          type: "phone"  },
  "10:41:7f": { vendor: "Apple",          type: "phone"  },
  "10:9a:dd": { vendor: "Apple",          type: "phone"  },
  "14:10:9f": { vendor: "Apple",          type: "phone"  },
  "14:5a:05": { vendor: "Apple",          type: "phone"  },
  "14:8f:c6": { vendor: "Apple",          type: "phone"  },
  "18:20:32": { vendor: "Apple",          type: "phone"  },
  "18:34:51": { vendor: "Apple",          type: "phone"  },
  "18:65:90": { vendor: "Apple",          type: "phone"  },
  "18:9e:fc": { vendor: "Apple",          type: "phone"  },
  "1c:1a:c0": { vendor: "Apple",          type: "phone"  },
  "1c:36:bb": { vendor: "Apple",          type: "phone"  },
  "1c:e6:2b": { vendor: "Apple",          type: "phone"  },
  "20:78:f0": { vendor: "Apple",          type: "phone"  },
  "20:9b:cd": { vendor: "Apple",          type: "phone"  },
  "24:a0:74": { vendor: "Apple",          type: "phone"  },
  "28:37:37": { vendor: "Apple",          type: "phone"  },
  "28:6a:b8": { vendor: "Apple",          type: "phone"  },
  "2c:be:08": { vendor: "Apple",          type: "phone"  },
  "34:12:98": { vendor: "Apple",          type: "phone"  },
  "34:36:3b": { vendor: "Apple",          type: "phone"  },
  "34:c0:59": { vendor: "Apple",          type: "phone"  },
  "38:0f:4a": { vendor: "Apple",          type: "phone"  },
  "38:48:4c": { vendor: "Apple",          type: "phone"  },
  "3c:15:c2": { vendor: "Apple",          type: "phone"  },
  "3c:2e:f9": { vendor: "Apple",          type: "phone"  },
  "40:30:04": { vendor: "Apple",          type: "phone"  },
  "40:33:1a": { vendor: "Apple",          type: "phone"  },
  "40:3c:fc": { vendor: "Apple",          type: "phone"  },
  "40:4d:7f": { vendor: "Apple",          type: "phone"  },
  "40:83:1d": { vendor: "Apple",          type: "phone"  },
  "40:9c:28": { vendor: "Apple",          type: "phone"  },
  "44:00:10": { vendor: "Apple",          type: "phone"  },
  "44:d8:84": { vendor: "Apple",          type: "phone"  },
  "48:43:7c": { vendor: "Apple",          type: "phone"  },
  "48:74:6e": { vendor: "Apple",          type: "phone"  },
  "4c:57:ca": { vendor: "Apple",          type: "phone"  },
  "4c:8d:79": { vendor: "Apple",          type: "phone"  },
  "50:82:d5": { vendor: "Apple",          type: "phone"  },
  "54:26:96": { vendor: "Apple",          type: "phone"  },
  "54:72:4f": { vendor: "Apple",          type: "phone"  },
  "5c:59:48": { vendor: "Apple",          type: "phone"  },
  "5c:f7:e6": { vendor: "Apple",          type: "phone"  },
  "60:33:4b": { vendor: "Apple",          type: "phone"  },
  "60:f4:45": { vendor: "Apple",          type: "phone"  },
  "60:fa:cd": { vendor: "Apple",          type: "phone"  },
  "64:76:ba": { vendor: "Apple",          type: "phone"  },
  "64:9a:be": { vendor: "Apple",          type: "phone"  },
  "64:a3:cb": { vendor: "Apple",          type: "phone"  },
  "68:96:7b": { vendor: "Apple",          type: "phone"  },
  "68:a8:6d": { vendor: "Apple",          type: "phone"  },
  "6c:40:08": { vendor: "Apple",          type: "phone"  },
  "6c:72:e7": { vendor: "Apple",          type: "phone"  },
  "70:14:a6": { vendor: "Apple",          type: "phone"  },
  "70:56:81": { vendor: "Apple",          type: "phone"  },
  "70:73:cb": { vendor: "Apple",          type: "phone"  },
  "70:ec:e4": { vendor: "Apple",          type: "phone"  },
  "74:1b:b2": { vendor: "Apple",          type: "phone"  },
  "74:e2:f5": { vendor: "Apple",          type: "phone"  },
  "78:31:c1": { vendor: "Apple",          type: "phone"  },
  "78:4f:43": { vendor: "Apple",          type: "phone"  },
  "78:ca:39": { vendor: "Apple",          type: "phone"  },
  "7c:04:d0": { vendor: "Apple",          type: "phone"  },
  "7c:6d:62": { vendor: "Apple",          type: "phone"  },
  "80:49:71": { vendor: "Apple",          type: "phone"  },
  "80:be:05": { vendor: "Apple",          type: "phone"  },
  "88:19:08": { vendor: "Apple",          type: "phone"  },
  "88:63:df": { vendor: "Apple",          type: "phone"  },
  "8c:00:6d": { vendor: "Apple",          type: "phone"  },
  "8c:7c:92": { vendor: "Apple",          type: "phone"  },
  "90:3c:92": { vendor: "Apple",          type: "phone"  },
  "90:72:40": { vendor: "Apple",          type: "phone"  },
  "94:bf:2d": { vendor: "Apple",          type: "phone"  },
  "98:01:a7": { vendor: "Apple",          type: "phone"  },
  "98:9e:63": { vendor: "Apple",          type: "phone"  },
  "9c:20:7b": { vendor: "Apple",          type: "phone"  },
  "9c:35:eb": { vendor: "Apple",          type: "phone"  },
  "a0:99:9b": { vendor: "Apple",          type: "phone"  },
  "a0:d7:95": { vendor: "Apple",          type: "phone"  },
  "a4:5e:60": { vendor: "Apple",          type: "phone"  },
  "a4:c3:61": { vendor: "Apple",          type: "phone"  },
  "a8:5b:4f": { vendor: "Apple",          type: "phone"  },
  "a8:8e:24": { vendor: "Apple",          type: "phone"  },
  "ac:37:43": { vendor: "Apple",          type: "phone"  },
  "ac:61:ea": { vendor: "Apple",          type: "phone"  },
  "ac:87:a3": { vendor: "Apple",          type: "phone"  },
  "ac:bc:32": { vendor: "Apple",          type: "phone"  },
  "b0:65:bd": { vendor: "Apple",          type: "phone"  },
  "b4:18:d1": { vendor: "Apple",          type: "phone"  },
  "b4:f0:ab": { vendor: "Apple",          type: "phone"  },
  "b8:53:ac": { vendor: "Apple",          type: "phone"  },
  "b8:c7:5d": { vendor: "Apple",          type: "phone"  },
  "b8:e8:56": { vendor: "Apple",          type: "phone"  },
  "bc:3b:af": { vendor: "Apple",          type: "phone"  },
  "bc:52:b7": { vendor: "Apple",          type: "phone"  },
  "c0:63:94": { vendor: "Apple",          type: "phone"  },
  "c0:84:7a": { vendor: "Apple",          type: "phone"  },
  "c4:2c:03": { vendor: "Apple",          type: "phone"  },
  "c8:bc:c8": { vendor: "Apple",          type: "phone"  },
  "cc:08:8d": { vendor: "Apple",          type: "phone"  },
  "cc:20:e8": { vendor: "Apple",          type: "phone"  },
  "d0:03:4b": { vendor: "Apple",          type: "phone"  },
  "d0:23:db": { vendor: "Apple",          type: "phone"  },
  "d4:61:9d": { vendor: "Apple",          type: "phone"  },
  "d4:9a:20": { vendor: "Apple",          type: "phone"  },
  "d4:dc:cd": { vendor: "Apple",          type: "phone"  },
  "d8:1d:72": { vendor: "Apple",          type: "phone"  },
  "d8:96:95": { vendor: "Apple",          type: "phone"  },
  "dc:2b:61": { vendor: "Apple",          type: "phone"  },
  "e0:b5:2d": { vendor: "Apple",          type: "phone"  },
  "e4:25:e7": { vendor: "Apple",          type: "phone"  },
  "e4:9a:79": { vendor: "Apple",          type: "phone"  },
  "e4:ce:8f": { vendor: "Apple",          type: "phone"  },
  "e8:04:62": { vendor: "Apple",          type: "phone"  },
  "ec:35:86": { vendor: "Apple",          type: "phone"  },
  "f0:b4:79": { vendor: "Apple",          type: "phone"  },
  "f0:cb:a1": { vendor: "Apple",          type: "phone"  },
  "f0:d1:a9": { vendor: "Apple",          type: "phone"  },
  "f4:37:b7": { vendor: "Apple",          type: "phone"  },
  "f4:f1:5a": { vendor: "Apple",          type: "phone"  },
  "f8:27:93": { vendor: "Apple",          type: "phone"  },
  "f8:2d:7c": { vendor: "Apple",          type: "phone"  },
  "fc:25:3f": { vendor: "Apple",          type: "phone"  },
  "fc:e9:98": { vendor: "Apple",          type: "phone"  },

  // Samsung
  "00:12:fb": { vendor: "Samsung",        type: "phone"  },
  "00:15:99": { vendor: "Samsung",        type: "phone"  },
  "00:17:c9": { vendor: "Samsung",        type: "phone"  },
  "00:21:19": { vendor: "Samsung",        type: "phone"  },
  "00:23:39": { vendor: "Samsung",        type: "phone"  },
  "08:08:c2": { vendor: "Samsung",        type: "phone"  },
  "08:37:3d": { vendor: "Samsung",        type: "phone"  },
  "08:d4:2b": { vendor: "Samsung",        type: "phone"  },
  "08:ec:a9": { vendor: "Samsung",        type: "phone"  },
  "0c:14:20": { vendor: "Samsung",        type: "phone"  },
  "10:30:47": { vendor: "Samsung",        type: "phone"  },
  "14:49:e0": { vendor: "Samsung",        type: "phone"  },
  "18:3a:2d": { vendor: "Samsung",        type: "phone"  },
  "20:13:e0": { vendor: "Samsung",        type: "phone"  },
  "20:64:32": { vendor: "Samsung",        type: "phone"  },
  "24:4b:03": { vendor: "Samsung",        type: "phone"  },
  "2c:0e:3d": { vendor: "Samsung",        type: "phone"  },
  "30:19:66": { vendor: "Samsung",        type: "phone"  },
  "34:be:00": { vendor: "Samsung",        type: "phone"  },
  "38:16:d1": { vendor: "Samsung",        type: "phone"  },
  "3c:5a:37": { vendor: "Samsung",        type: "phone"  },
  "40:0e:85": { vendor: "Samsung",        type: "phone"  },
  "4c:3c:16": { vendor: "Samsung",        type: "phone"  },
  "50:01:bb": { vendor: "Samsung",        type: "phone"  },
  "50:32:37": { vendor: "Samsung",        type: "phone"  },
  "50:a4:c8": { vendor: "Samsung",        type: "phone"  },
  "54:88:0e": { vendor: "Samsung",        type: "phone"  },
  "54:92:be": { vendor: "Samsung",        type: "phone"  },
  "5c:49:7d": { vendor: "Samsung",        type: "phone"  },
  "5c:f6:dc": { vendor: "Samsung",        type: "phone"  },
  "60:6b:bd": { vendor: "Samsung",        type: "phone"  },
  "60:a1:0a": { vendor: "Samsung",        type: "phone"  },
  "64:b3:10": { vendor: "Samsung",        type: "phone"  },
  "68:27:37": { vendor: "Samsung",        type: "phone"  },
  "6c:f3:73": { vendor: "Samsung",        type: "phone"  },
  "70:f9:27": { vendor: "Samsung",        type: "phone"  },
  "78:1f:db": { vendor: "Samsung",        type: "phone"  },
  "7c:0b:c6": { vendor: "Samsung",        type: "phone"  },
  "84:25:db": { vendor: "Samsung",        type: "phone"  },
  "84:38:38": { vendor: "Samsung",        type: "phone"  },
  "88:32:9b": { vendor: "Samsung",        type: "phone"  },
  "88:36:6c": { vendor: "Samsung",        type: "phone"  },
  "8c:71:f8": { vendor: "Samsung",        type: "phone"  },
  "90:18:7c": { vendor: "Samsung",        type: "phone"  },
  "94:35:0a": { vendor: "Samsung",        type: "phone"  },
  "94:76:b7": { vendor: "Samsung",        type: "phone"  },
  "94:d7:71": { vendor: "Samsung",        type: "phone"  },
  "98:52:b1": { vendor: "Samsung",        type: "phone"  },
  "9c:02:98": { vendor: "Samsung",        type: "phone"  },
  "9c:3a:af": { vendor: "Samsung",        type: "phone"  },
  "a0:07:98": { vendor: "Samsung",        type: "phone"  },
  "a0:0b:ba": { vendor: "Samsung",        type: "phone"  },
  "a0:75:91": { vendor: "Samsung",        type: "phone"  },
  "a4:07:b6": { vendor: "Samsung",        type: "phone"  },
  "ac:5f:3e": { vendor: "Samsung",        type: "phone"  },
  "b0:72:bf": { vendor: "Samsung",        type: "phone"  },
  "b0:c5:59": { vendor: "Samsung",        type: "phone"  },
  "b0:df:3a": { vendor: "Samsung",        type: "phone"  },
  "b4:3a:28": { vendor: "Samsung",        type: "phone"  },
  "b8:5e:7b": { vendor: "Samsung",        type: "phone"  },
  "bc:20:a4": { vendor: "Samsung",        type: "phone"  },
  "bc:44:86": { vendor: "Samsung",        type: "phone"  },
  "bc:72:b1": { vendor: "Samsung",        type: "phone"  },
  "bc:85:56": { vendor: "Samsung",        type: "phone"  },
  "c0:bd:d1": { vendor: "Samsung",        type: "phone"  },
  "c4:42:02": { vendor: "Samsung",        type: "phone"  },
  "c4:50:06": { vendor: "Samsung",        type: "phone"  },
  "c4:57:6e": { vendor: "Samsung",        type: "phone"  },
  "c4:88:e5": { vendor: "Samsung",        type: "phone"  },
  "c8:19:f7": { vendor: "Samsung",        type: "phone"  },
  "cc:07:ab": { vendor: "Samsung",        type: "phone"  },
  "d0:22:be": { vendor: "Samsung",        type: "phone"  },
  "d0:59:e4": { vendor: "Samsung",        type: "phone"  },
  "d8:57:ef": { vendor: "Samsung",        type: "phone"  },
  "dc:71:96": { vendor: "Samsung",        type: "phone"  },
  "e4:12:1d": { vendor: "Samsung",        type: "phone"  },
  "e4:92:fb": { vendor: "Samsung",        type: "phone"  },
  "e8:03:9a": { vendor: "Samsung",        type: "phone"  },
  "ec:1f:72": { vendor: "Samsung",        type: "phone"  },
  "f0:25:b7": { vendor: "Samsung",        type: "phone"  },
  "f4:42:8f": { vendor: "Samsung",        type: "phone"  },
  "f4:7b:5e": { vendor: "Samsung",        type: "phone"  },
  "f8:04:2f": { vendor: "Samsung",        type: "phone"  },
  "f8:77:b8": { vendor: "Samsung",        type: "phone"  },
  "fc:a1:3e": { vendor: "Samsung",        type: "phone"  },

  // Xiaomi / Redmi / POCO
  "00:9e:c8": { vendor: "Xiaomi",         type: "phone"  },
  "0c:1d:af": { vendor: "Xiaomi",         type: "phone"  },
  "10:2a:b3": { vendor: "Xiaomi",         type: "phone"  },
  "14:f6:5a": { vendor: "Xiaomi",         type: "phone"  },
  "18:59:36": { vendor: "Xiaomi",         type: "phone"  },
  "20:82:c0": { vendor: "Xiaomi",         type: "phone"  },
  "28:6c:07": { vendor: "Xiaomi",         type: "phone"  },
  "34:80:b3": { vendor: "Xiaomi",         type: "phone"  },
  "38:a4:ed": { vendor: "Xiaomi",         type: "phone"  },
  "3c:bd:d8": { vendor: "Xiaomi",         type: "phone"  },
  "40:31:3c": { vendor: "Xiaomi",         type: "phone"  },
  "44:00:49": { vendor: "Xiaomi",         type: "phone"  },
  "50:64:2b": { vendor: "Xiaomi",         type: "phone"  },
  "54:a0:50": { vendor: "Xiaomi",         type: "phone"  },
  "58:44:98": { vendor: "Xiaomi",         type: "phone"  },
  "64:09:80": { vendor: "Xiaomi",         type: "phone"  },
  "64:b4:73": { vendor: "Xiaomi",         type: "phone"  },
  "68:df:dd": { vendor: "Xiaomi",         type: "phone"  },
  "74:23:44": { vendor: "Xiaomi",         type: "phone"  },
  "74:51:ba": { vendor: "Xiaomi",         type: "phone"  },
  "78:02:f8": { vendor: "Xiaomi",         type: "phone"  },
  "7c:1d:d9": { vendor: "Xiaomi",         type: "phone"  },
  "80:35:c1": { vendor: "Xiaomi",         type: "phone"  },
  "98:fa:e3": { vendor: "Xiaomi",         type: "phone"  },
  "9c:99:a0": { vendor: "Xiaomi",         type: "phone"  },
  "a0:86:c6": { vendor: "Xiaomi",         type: "phone"  },
  "ac:c1:ee": { vendor: "Xiaomi",         type: "phone"  },
  "b0:e2:35": { vendor: "Xiaomi",         type: "phone"  },
  "c4:6a:b7": { vendor: "Xiaomi",         type: "phone"  },
  "d4:97:0b": { vendor: "Xiaomi",         type: "phone"  },
  "e4:46:da": { vendor: "Xiaomi",         type: "phone"  },
  "f0:b4:29": { vendor: "Xiaomi",         type: "phone"  },
  "f4:8b:32": { vendor: "Xiaomi",         type: "phone"  },
  "f8:a4:5f": { vendor: "Xiaomi",         type: "phone"  },
  "fc:64:ba": { vendor: "Xiaomi",         type: "phone"  },

  // OnePlus
  "04:d6:aa": { vendor: "OnePlus",        type: "phone"  },
  "08:f3:fb": { vendor: "OnePlus",        type: "phone"  },
  "1c:77:f6": { vendor: "OnePlus",        type: "phone"  },
  "38:01:46": { vendor: "OnePlus",        type: "phone"  },
  "50:14:79": { vendor: "OnePlus",        type: "phone"  },
  "64:a2:f9": { vendor: "OnePlus",        type: "phone"  },
  "94:65:2d": { vendor: "OnePlus",        type: "phone"  },
  "ac:be:8e": { vendor: "OnePlus",        type: "phone"  },
  "c0:ee:fb": { vendor: "OnePlus",        type: "phone"  },

  // Realme / OPPO
  "00:1a:ef": { vendor: "OPPO",           type: "phone"  },
  "0c:1d:af": { vendor: "OPPO",           type: "phone"  },
  "28:ba:b5": { vendor: "OPPO",           type: "phone"  },
  "34:d3:0c": { vendor: "OPPO",           type: "phone"  },
  "48:db:50": { vendor: "OPPO",           type: "phone"  },
  "58:2f:40": { vendor: "OPPO",           type: "phone"  },
  "64:90:c1": { vendor: "Realme",         type: "phone"  },
  "70:3e:ac": { vendor: "OPPO",           type: "phone"  },
  "84:cf:bf": { vendor: "OPPO",           type: "phone"  },
  "90:e7:c4": { vendor: "Realme",         type: "phone"  },
  "a8:9c:ed": { vendor: "OPPO",           type: "phone"  },
  "c0:ee:40": { vendor: "OPPO",           type: "phone"  },
  "cc:34:d7": { vendor: "OPPO",           type: "phone"  },
  "e8:bb:a8": { vendor: "OPPO",           type: "phone"  },

  // Vivo
  "18:68:cb": { vendor: "Vivo",           type: "phone"  },
  "30:74:96": { vendor: "Vivo",           type: "phone"  },
  "38:56:10": { vendor: "Vivo",           type: "phone"  },
  "58:2f:40": { vendor: "Vivo",           type: "phone"  },
  "7c:83:34": { vendor: "Vivo",           type: "phone"  },
  "90:09:17": { vendor: "Vivo",           type: "phone"  },
  "c0:9a:d0": { vendor: "Vivo",           type: "phone"  },
  "e4:70:b8": { vendor: "Vivo",           type: "phone"  },
  "ec:6b:5f": { vendor: "Vivo",           type: "phone"  },
  "f0:77:c3": { vendor: "Vivo",           type: "phone"  },

  // Huawei / Honor
  "00:18:82": { vendor: "Huawei",         type: "phone"  },
  "00:46:4b": { vendor: "Huawei",         type: "phone"  },
  "00:e0:fc": { vendor: "Huawei",         type: "phone"  },
  "04:02:1f": { vendor: "Huawei",         type: "phone"  },
  "04:c0:6f": { vendor: "Huawei",         type: "phone"  },
  "04:f9:38": { vendor: "Huawei",         type: "phone"  },
  "0c:96:bf": { vendor: "Huawei",         type: "phone"  },
  "10:1b:54": { vendor: "Huawei",         type: "phone"  },
  "14:9d:09": { vendor: "Huawei",         type: "phone"  },
  "18:ded8":  { vendor: "Huawei",         type: "phone"  },
  "20:f1:7c": { vendor: "Huawei",         type: "phone"  },
  "2c:9d:1e": { vendor: "Huawei",         type: "phone"  },
  "34:6a:c2": { vendor: "Huawei",         type: "phone"  },
  "38:f8:89": { vendor: "Huawei",         type: "phone"  },
  "3c:5e:c3": { vendor: "Huawei",         type: "phone"  },
  "40:4d:8e": { vendor: "Huawei",         type: "phone"  },
  "48:46:fb": { vendor: "Huawei",         type: "phone"  },
  "4c:1b:86": { vendor: "Huawei",         type: "phone"  },
  "50:a7:2b": { vendor: "Huawei",         type: "phone"  },
  "54:25:ea": { vendor: "Huawei",         type: "phone"  },
  "5c:c3:07": { vendor: "Huawei",         type: "phone"  },
  "60:de:44": { vendor: "Huawei",         type: "phone"  },
  "68:cc:6e": { vendor: "Huawei",         type: "phone"  },
  "70:7b:e8": { vendor: "Huawei",         type: "phone"  },
  "78:1d:ba": { vendor: "Huawei",         type: "phone"  },
  "7c:1c:f1": { vendor: "Huawei",         type: "phone"  },
  "80:38:bc": { vendor: "Huawei",         type: "phone"  },
  "84:a8:e4": { vendor: "Huawei",         type: "phone"  },
  "88:53:2e": { vendor: "Huawei",         type: "phone"  },
  "8c:34:fd": { vendor: "Huawei",         type: "phone"  },
  "90:17:ac": { vendor: "Huawei",         type: "phone"  },
  "9c:28:ef": { vendor: "Huawei",         type: "phone"  },
  "a0:08:6f": { vendor: "Huawei",         type: "phone"  },
  "a4:50:46": { vendor: "Huawei",         type: "phone"  },
  "a8:9f:ec": { vendor: "Huawei",         type: "phone"  },
  "b0:e5:ed": { vendor: "Huawei",         type: "phone"  },
  "bc:7e:8b": { vendor: "Huawei",         type: "phone"  },
  "c0:70:09": { vendor: "Huawei",         type: "phone"  },
  "c4:07:2f": { vendor: "Huawei",         type: "phone"  },
  "c8:51:95": { vendor: "Huawei",         type: "phone"  },
  "cc:96:a0": { vendor: "Huawei",         type: "phone"  },
  "d0:27:88": { vendor: "Huawei",         type: "phone"  },
  "e4:a7:c5": { vendor: "Huawei",         type: "phone"  },
  "e8:cd:2d": { vendor: "Huawei",         type: "phone"  },
  "ec:23:3d": { vendor: "Huawei",         type: "phone"  },
  "f4:cb:52": { vendor: "Huawei",         type: "phone"  },
  "f4:e3:fb": { vendor: "Huawei",         type: "phone"  },
  "f8:23:b2": { vendor: "Huawei",         type: "phone"  },
  "fc:3f:7c": { vendor: "Huawei",         type: "phone"  },

  // Google Pixel
  "00:1a:11": { vendor: "Google",         type: "phone"  },
  "3c:5a:b4": { vendor: "Google",         type: "phone"  },
  "54:60:09": { vendor: "Google",         type: "phone"  },
  "94:eb:cd": { vendor: "Google",         type: "phone"  },
  "f8:8f:ca": { vendor: "Google",         type: "phone"  },

  // Dell laptops
  "00:14:22": { vendor: "Dell",           type: "laptop" },
  "00:1a:4b": { vendor: "Dell",           type: "laptop" },
  "00:21:70": { vendor: "Dell",           type: "laptop" },
  "14:18:77": { vendor: "Dell",           type: "laptop" },
  "18:03:73": { vendor: "Dell",           type: "laptop" },
  "18:66:da": { vendor: "Dell",           type: "laptop" },
  "20:47:47": { vendor: "Dell",           type: "laptop" },
  "24:b6:fd": { vendor: "Dell",           type: "laptop" },
  "28:f1:0e": { vendor: "Dell",           type: "laptop" },
  "44:8a:5b": { vendor: "Dell",           type: "laptop" },
  "4c:ed:fb": { vendor: "Dell",           type: "laptop" },
  "54:bf:64": { vendor: "Dell",           type: "laptop" },
  "5c:f9:dd": { vendor: "Dell",           type: "laptop" },
  "60:03:08": { vendor: "Dell",           type: "laptop" },
  "74:86:7a": { vendor: "Dell",           type: "laptop" },
  "78:2b:cb": { vendor: "Dell",           type: "laptop" },
  "84:7b:eb": { vendor: "Dell",           type: "laptop" },
  "90:b1:1c": { vendor: "Dell",           type: "laptop" },
  "b0:83:fe": { vendor: "Dell",           type: "laptop" },
  "b8:ca:3a": { vendor: "Dell",           type: "laptop" },
  "c8:1f:66": { vendor: "Dell",           type: "laptop" },
  "d4:be:d9": { vendor: "Dell",           type: "laptop" },
  "e0:db:55": { vendor: "Dell",           type: "laptop" },
  "e4:b9:7a": { vendor: "Dell",           type: "laptop" },
  "f0:1f:af": { vendor: "Dell",           type: "laptop" },
  "f8:db:88": { vendor: "Dell",           type: "laptop" },

  // Lenovo
  "00:23:ae": { vendor: "Lenovo",         type: "laptop" },
  "18:5e:0f": { vendor: "Lenovo",         type: "laptop" },
  "28:d2:44": { vendor: "Lenovo",         type: "laptop" },
  "40:8d:5c": { vendor: "Lenovo",         type: "laptop" },
  "48:0f:cf": { vendor: "Lenovo",         type: "laptop" },
  "48:51:b7": { vendor: "Lenovo",         type: "laptop" },
  "54:e1:ad": { vendor: "Lenovo",         type: "laptop" },
  "5c:f3:70": { vendor: "Lenovo",         type: "laptop" },
  "70:5a:0f": { vendor: "Lenovo",         type: "laptop" },
  "80:fa:5b": { vendor: "Lenovo",         type: "laptop" },
  "84:7a:88": { vendor: "Lenovo",         type: "laptop" },
  "88:70:8c": { vendor: "Lenovo",         type: "laptop" },
  "90:2b:34": { vendor: "Lenovo",         type: "laptop" },
  "98:e7:f4": { vendor: "Lenovo",         type: "laptop" },
  "a0:4e:a7": { vendor: "Lenovo",         type: "laptop" },
  "a4:4c:11": { vendor: "Lenovo",         type: "laptop" },
  "c8:5b:76": { vendor: "Lenovo",         type: "laptop" },
  "d0:53:49": { vendor: "Lenovo",         type: "laptop" },
  "e0:94:67": { vendor: "Lenovo",         type: "laptop" },
  "f4:8c:50": { vendor: "Lenovo",         type: "laptop" },

  // HP
  "00:1f:29": { vendor: "HP",             type: "laptop" },
  "10:60:4b": { vendor: "HP",             type: "laptop" },
  "18:a9:05": { vendor: "HP",             type: "laptop" },
  "30:8d:99": { vendor: "HP",             type: "laptop" },
  "38:63:bb": { vendor: "HP",             type: "laptop" },
  "40:b0:34": { vendor: "HP",             type: "laptop" },
  "48:0f:cf": { vendor: "HP",             type: "laptop" },
  "50:65:f3": { vendor: "HP",             type: "laptop" },
  "70:5a:b6": { vendor: "HP",             type: "laptop" },
  "78:92:9c": { vendor: "HP",             type: "laptop" },
  "80:ce:62": { vendor: "HP",             type: "laptop" },
  "98:4b:e1": { vendor: "HP",             type: "laptop" },
  "9c:b6:54": { vendor: "HP",             type: "laptop" },
  "a0:d3:c1": { vendor: "HP",             type: "laptop" },
  "b4:99:ba": { vendor: "HP",             type: "laptop" },
  "c8:cb:9e": { vendor: "HP",             type: "laptop" },
  "d8:d1:cb": { vendor: "HP",             type: "laptop" },

  // Asus
  "00:17:31": { vendor: "ASUS",           type: "laptop" },
  "00:22:15": { vendor: "ASUS",           type: "laptop" },
  "04:92:26": { vendor: "ASUS",           type: "laptop" },
  "08:60:6e": { vendor: "ASUS",           type: "laptop" },
  "10:bf:48": { vendor: "ASUS",           type: "laptop" },
  "14:da:e9": { vendor: "ASUS",           type: "laptop" },
  "2c:56:dc": { vendor: "ASUS",           type: "laptop" },
  "30:85:a9": { vendor: "ASUS",           type: "laptop" },
  "38:d5:47": { vendor: "ASUS",           type: "laptop" },
  "40:16:7e": { vendor: "ASUS",           type: "laptop" },
  "4c:ed:de": { vendor: "ASUS",           type: "laptop" },
  "50:46:5d": { vendor: "ASUS",           type: "laptop" },
  "5c:ff:35": { vendor: "ASUS",           type: "laptop" },
  "74:d0:2b": { vendor: "ASUS",           type: "laptop" },
  "78:24:af": { vendor: "ASUS",           type: "laptop" },
  "7c:10:c9": { vendor: "ASUS",           type: "laptop" },
  "ac:22:0b": { vendor: "ASUS",           type: "laptop" },
  "bc:ee:7b": { vendor: "ASUS",           type: "laptop" },
  "e8:9a:8f": { vendor: "ASUS",           type: "laptop" },
  "f8:28:19": { vendor: "ASUS",           type: "laptop" },

  // Raspberry Pi / Linux SBCs
  "b8:27:eb": { vendor: "Raspberry Pi",   type: "iot"    },
  "dc:a6:32": { vendor: "Raspberry Pi",   type: "iot"    },
  "e4:5f:01": { vendor: "Raspberry Pi",   type: "iot"    },

  // Misc
  "00:50:56": { vendor: "VMware",         type: "pc"     },
  "00:0c:29": { vendor: "VMware",         type: "pc"     },
  "00:15:5d": { vendor: "Microsoft (Hyper-V)", type: "pc" },
  "52:54:00": { vendor: "QEMU/KVM",       type: "pc"     },
  "08:00:27": { vendor: "VirtualBox",     type: "pc"     },
};

/**
 * Look up vendor info for a MAC address.
 * Handles locally-administered (randomized) MACs gracefully.
 *
 * @param {string} mac - full MAC, e.g. "e6:83:4c:f9:c1:11"
 * @returns {{ vendor: string, type: string, isRandomized: boolean }}
 */
function lookupOUI(mac) {
  if (!mac || mac === "??:??:??:??:??:??") {
    return { vendor: "Unknown", type: "unknown", isRandomized: false };
  }

  const clean = mac.toLowerCase().trim();

  // Check if locally-administered (randomized) MAC
  // Second bit of first octet is 1 for locally administered
  const firstOctet = parseInt(clean.split(":")[0] || clean.split("-")[0], 16);
  if ((firstOctet & 0x02) !== 0) {
    return { vendor: "Unknown (Randomized MAC)", type: "phone", isRandomized: true };
  }

  // Normalize to colon-separated lowercase
  const normalized = clean.replace(/-/g, ":").substring(0, 8);
  const entry = OUI_DB[normalized];

  if (entry) return { ...entry, isRandomized: false };

  // Try 2-octet prefix for partial matches
  const shortPrefix = normalized.substring(0, 5);
  for (const [key, val] of Object.entries(OUI_DB)) {
    if (key.substring(0, 5) === shortPrefix) {
      return { ...val, isRandomized: false };
    }
  }

  return { vendor: "Unknown", type: "unknown", isRandomized: false };
}

/**
 * Get a device type emoji based on vendor type.
 */
function typeToEmoji(type, vendor) {
  switch (type) {
    case "phone":  return "📱";
    case "tablet": return "📟";
    case "laptop": return "💻";
    case "router": return "📡";
    case "iot":    return "🔌";
    case "pc":     return "🖥";
    default:       return "📡";
  }
}

/**
 * Generate a friendly default name from vendor + MAC suffix.
 */
function vendorToName(vendor, mac, type) {
  const suffix = mac ? mac.replace(/:/g, "").slice(-4).toUpperCase() : "????";

  if (vendor === "Unknown" || vendor.startsWith("Unknown")) {
    return `Device-${suffix}`;
  }

  const typeLabel = type === "phone"  ? "Phone"
                  : type === "laptop" ? "Laptop"
                  : type === "tablet" ? "Tablet"
                  : type === "iot"    ? "Device"
                  : "Device";

  return `${vendor} ${typeLabel}`;
}

module.exports = { lookupOUI, typeToEmoji, vendorToName };
